// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using POC_Data.Context;

namespace Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210902225600_AddProductIamgeAndCompanyTablesToDb")]
    partial class AddProductIamgeAndCompanyTablesToDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("POC_Models.Models.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Company 1"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Company 2"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Company 3"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Company 4"
                        });
                });

            modelBuilder.Entity("POC_Models.Models.ProductImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte[]>("Image")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<int?>("ProductImageId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductImageId")
                        .IsUnique()
                        .HasFilter("[ProductImageId] IS NOT NULL");

                    b.ToTable("ProductImages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Image = new byte[] { 32, 32, 32, 32, 32 }
                        },
                        new
                        {
                            Id = 2,
                            Image = new byte[] { 32, 32, 32, 32, 32 }
                        },
                        new
                        {
                            Id = 3,
                            Image = new byte[] { 32, 32, 32, 32, 32 }
                        },
                        new
                        {
                            Id = 4,
                            Image = new byte[] { 32, 32, 32, 32, 32 }
                        });
                });

            modelBuilder.Entity("POC_Models.Models.Toys", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AgeRestriction")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,6)");

                    b.Property<int>("ProductImageId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Toys");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AgeRestriction = 5,
                            CompanyId = 1,
                            Description = "This is a toy",
                            Name = "MyToy 1",
                            Price = 15m,
                            ProductImageId = 1
                        },
                        new
                        {
                            Id = 2,
                            AgeRestriction = 5,
                            CompanyId = 2,
                            Description = "This is a toy",
                            Name = "MyToy 2",
                            Price = 15m,
                            ProductImageId = 2
                        },
                        new
                        {
                            Id = 3,
                            AgeRestriction = 5,
                            CompanyId = 3,
                            Description = "This is a toy",
                            Name = "MyToy 3",
                            Price = 15m,
                            ProductImageId = 3
                        },
                        new
                        {
                            Id = 4,
                            AgeRestriction = 5,
                            CompanyId = 4,
                            Description = "This is a toy",
                            Name = "MyToy 4",
                            Price = 15m,
                            ProductImageId = 4
                        });
                });

            modelBuilder.Entity("POC_Models.Models.ProductImage", b =>
                {
                    b.HasOne("POC_Models.Models.Toys", "Toys")
                        .WithOne("ProductImage")
                        .HasForeignKey("POC_Models.Models.ProductImage", "ProductImageId");

                    b.Navigation("Toys");
                });

            modelBuilder.Entity("POC_Models.Models.Toys", b =>
                {
                    b.HasOne("POC_Models.Models.Company", "Company")
                        .WithMany("Toys")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("POC_Models.Models.Company", b =>
                {
                    b.Navigation("Toys");
                });

            modelBuilder.Entity("POC_Models.Models.Toys", b =>
                {
                    b.Navigation("ProductImage");
                });
#pragma warning restore 612, 618
        }
    }
}
